<script setup lang="ts">
import { projects } from '~/data/projects'
useSeoMeta({title:'OracleSteps | Enterprise Software Solutions & Digital Transformation',ogTitle:'OracleSteps | Enterprise Software Solutions & Engineering',description:'OracleSteps crafts scalable, high-performance web applications, AI-powered financial tools, transport logistics platforms, and enterprise data analytics software.',ogDescription:'Enterprise software engineering for transport, financial services, logistics and data analytics.'})
const services=[{title:'Enterprise web engineering',text:'Reliable web applications tailored to your operations, your customers, and the scale of your business.'},{title:'AI & machine learning',text:'Predictive models, transaction risk scoring, and practical AI workflows integrated into your software.'},{title:'Cloud infrastructure & DevOps',text:'Scalable cloud architecture, automated deployments, and infrastructure built for operational continuity.'},{title:'Data science & analytics',text:'Statistical computing, data pipelines, and reporting platforms that make complex information usable.'}]
</script>
<template><div>
 <section class="hero"><img class="hero-photo" src="/images/template-hero.jpg" alt="" fetchpriority="high" width="1400" height="1000"><div class="container hero-content"><h1>Experience & excellence</h1><p>Enterprise software. Thoughtful engineering. Lasting impact.</p><div class="hero-actions"><a class="button secondary" href="#work">Explore our work</a><NuxtLink class="button primary" to="/contact">Start your project</NuxtLink></div></div></section>
 <section class="section container company-intro"><div class="section-heading"><h2>Software built around your business</h2><p>OracleSteps builds software for organisations solving complex problems. We bring enterprise architecture, modern web development, and artificial intelligence together to deliver platforms that work at scale.</p></div><div class="principles"><article><h3>Reliable by design</h3><p>Mission-critical systems built for operational continuity.</p></article><article><h3>Ready to grow</h3><p>Modular platforms that adapt as your business expands.</p></article><article><h3>Security from the start</h3><p>Security and compliance considered from architecture through delivery.</p></article></div></section>
 <section id="work" class="section work-section"><div class="container"><div class="section-heading"><h2>Recent work</h2><p>Selected projects across public transport, financial services, global business, and data science.</p></div><div class="projects-grid"><ProjectCard v-for="project in projects" :key="project.id" :project="project"/></div><div class="section-action"><NuxtLink class="button outline" to="/about-work">View our portfolio</NuxtLink></div></div></section>
 <section id="services" class="section container"><div class="section-heading"><h2>What we do</h2><p>From architecture and development to deployment and ongoing growth.</p></div><div class="services-grid"><article v-for="service in services" :key="service.title"><h3>{{service.title}}</h3><p>{{service.text}}</p></article></div></section>
 <section class="facts-section"><div class="container"><div class="section-heading"><h2>Engineering at scale</h2></div><div class="metrics"><div><span class="metric-number">99.99%</span><p>Platform uptime ensured</p></div><div><span class="metric-number">4+</span><p>Enterprise-scale systems deployed</p></div><div><span class="metric-number">Millions+</span><p>Daily transactions & users handled</p></div></div></div></section>
 <ContactBanner/>
</div></template>
